import 'dart:io';
import 'package:path/path.dart' as path;
import '../../domain/entities/project_config.dart';

/// Writes an AI-agent rules file (same content, per-agent filename) capturing
/// the project's conventions so any agent follows the vgv_cli pattern.
class AgentRulesGenerator {
  const AgentRulesGenerator();

  Future<void> generate(ProjectConfig config) async {
    if (config.aiAgents.isEmpty) return;
    final content = _rules(config);
    for (final agent in config.aiAgents) {
      final file = File(path.join(config.projectName, agent.rulesFilePath))
        ..parent.createSync(recursive: true);
      file.writeAsStringSync(content);
    }
  }

  String _rules(ProjectConfig config) => '''# Project rules for AI coding agents

Generated by vgv_cli. Follow these conventions strictly when editing this
project — they mirror the architecture the project was scaffolded with.

## Architecture — Clean Architecture (per feature)
Every feature lives under `lib/features/<feature>/` split in three layers:
- `domain/` — `entities/` (pure `@freezed`), `repositories/` (abstract),
  `use_cases/`.
- `data/` — `datasources/` (remote/local), `models/` (`@freezed` +
  `fromJson`/`toJson`/`fromEntity`/`toEntity`), `repositories/` (impl).
- `presentation/` — `blocs/`, `pages/`, `widgets/`.

Never put business logic in the UI layer. UI → BLoC → use case → repository →
datasource.

## State management
- ❌ **Never use `setState`** — it rebuilds the whole widget subtree.
- ✅ **BLoC** (`flutter_bloc`) for state shared across widgets/screens.
- ✅ **`ValueNotifier` + `ValueListenableBuilder`** for state local to a single
  widget (e.g. a toggle, a text field's state).
- BLoC **state** and **events** use **`freezed`** (events may be a sealed
  class or `@freezed`); states are `@freezed` with `@Default(...)`.

## Widgets — use the provided base classes
- ❌ Do **not** extend `StatelessWidget` / `StatefulWidget` directly.
- ✅ Extend **`TStateless`** / **`TStatefull`** (in `lib/core/states/`). They
  give you a ready `bodyWidget(BuildContext context, ThemeData theme, S translation)`
  so theme and translations are always in scope:

```dart
class ProfileView extends TStateless {
  const ProfileView({super.key});

  @override
  Bloc? get bloc => null; // or the feature's BLoC

  @override
  Widget bodyWidget(BuildContext context, ThemeData theme, S translation) {
    return Text(translation.someKey);
  }
}
```

## Models & entities
- **Entity** (`domain/entities/`): `@freezed`, PURE domain — no `fromJson`.
- **Model** (`data/models/`): `@freezed` with `@JsonKey`, owning
  `fromJson`/`toJson` **and** `fromEntity`/`toEntity`.

## Internationalization
- Use **intl_utils**: never hardcode user-facing strings. Access via
  `S.of(context)` (the `translation` param in `bodyWidget`). Add keys to the
  `.arb` files and run codegen.

## Navigation
- Use **GoRouter** through `AppRoutes` (see `lib/application/routes/`). Do not
  push raw `MaterialPageRoute`s for app navigation.

## Dependency injection
- Register/resolve dependencies through the `Injector` (get_it). Do not
  instantiate repositories/use cases directly in the UI.

## Flavors & entry points
- Flavors: ${config.flavors.map((f) => f.flavorName).join(', ')}. Run with
  `flutter run --flavor <flavor> -t lib/main_<entryPoint>.dart`. Keep
  environment-specific config in `AppConfiguration` / `AppEnvironment`.

## Code generation
- After changing any `@freezed`, `json_serializable` or Drift code, run:
  `dart run build_runner build -d` (or `--delete-conflicting-outputs`).

## Golden rule
Match the existing patterns in the codebase. When in doubt, look at the
`auth` feature for the reference implementation.
''';
}
