import 'dart:convert';
import 'dart:io';

import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as p;

import '../templates/screenshot_script.dart';
import 'screenshot_web.dart';

/// Runs `vgv screenshots`: frames raw app screenshots into store-ready
/// marketing posters via the bundled Pillow script. Works on ANY Flutter
/// project (input = raw PNGs + a manifest); no dependency on the vgv template.
class ScreenshotRunner {
  ScreenshotRunner({Logger? logger}) : _logger = logger ?? Logger();

  final Logger _logger;

  Future<int> run(List<String> args) async {
    if (args.isEmpty || args.first == '-h' || args.first == '--help') {
      _usage();
      return args.isEmpty ? 1 : 0;
    }
    if (args.first == '--init') {
      _init(args.length > 1 ? args[1] : 'store_screenshots');
      return 0;
    }
    if (args.first == 'capture') {
      return _capture(args.sublist(1));
    }
    if (args.first == 'web') {
      return ScreenshotWebServer(logger: _logger).run(args.sublist(1));
    }

    final manifest = args.first;
    if (!File(manifest).existsSync()) {
      _logger
        ..err('Manifest not found: $manifest')
        ..info(styleDim.wrap('  Create one with: vgv screenshots --init'));
      return 1;
    }

    // Tooling: python3 + Pillow (we don't auto-install — instruct instead).
    if (!await _has('python3')) {
      _logger
        ..err('python3 was not found on your PATH.')
        ..info(styleDim.wrap('  macOS ships Python 3. Otherwise: brew install python'));
      return 1;
    }
    final pillow = await Process.run(
        'python3', ['-c', 'import PIL'], runInShell: true);
    if (pillow.exitCode != 0) {
      _logger
        ..err('Python Pillow is not installed.')
        ..info(styleDim.wrap('  Install it: python3 -m pip install --user pillow'));
      return 1;
    }

    // Write the bundled script to a temp file and run it.
    final script = File(p.join(Directory.systemTemp.path, 'vgv_frame_screenshots.py'));
    script.writeAsBytesSync(base64.decode(frameScreenshotsPyBase64));

    _logger.info(styleBold.wrap(lightCyan.wrap('  📸 Rendering store screenshots…')));
    final result = await Process.run(
        'python3', [script.path, 'manifest', manifest], runInShell: true);

    if (result.exitCode == 0) {
      for (final line in result.stdout.toString().trim().split('\n')) {
        if (line.trim().isNotEmpty) _logger.info('    ${green.wrap('✓')} $line');
      }
      _logger
        ..info('')
        ..info(green.wrap('  Done — store-ready posters generated.'))
        ..info('');
    } else {
      _logger
        ..err('  Screenshot generation failed:')
        ..err(result.stderr.toString());
    }
    return result.exitCode;
  }

  /// `vgv screenshots capture` — scaffold/run a golden harness that renders
  /// the app's own screens to raw PNGs (which then feed the framing manifest).
  Future<int> _capture(List<String> args) async {
    const harnessPath = 'test/store_capture_test.dart';
    if (args.isEmpty || args.first == '--init') {
      final file = File(harnessPath);
      if (file.existsSync() && !(args.contains('--force'))) {
        _logger.err('$harnessPath already exists (use --force to overwrite).');
        return 1;
      }
      (file..parent.createSync(recursive: true))
          .writeAsStringSync(_captureHarness());
      _logger
        ..info('')
        ..info(green.wrap('  Scaffolded $harnessPath')!)
        ..info('    ${styleDim.wrap('1. Wire your real screens + DI inside it (replace the Placeholder).')}')
        ..info('    2. Capture: ${lightCyan.wrap('vgv screenshots capture $harnessPath')}')
        ..info('    ${styleDim.wrap('Raw PNGs land in store_shots/raw/ — point your manifest there.')}')
        ..info('');
      return 0;
    }

    final testPath = args.first;
    if (!File(testPath).existsSync()) {
      _logger.err('Test harness not found: $testPath');
      return 1;
    }
    if (!await _has('flutter')) {
      _logger.err('flutter was not found on your PATH.');
      return 1;
    }
    _logger.info(styleBold.wrap(lightCyan.wrap('  📸 Capturing raw screens (flutter test --update-goldens)…'))!);
    final result = await Process.run(
        'flutter', <String>['test', '--update-goldens', testPath],
        runInShell: true);
    if (result.exitCode == 0) {
      _logger
        ..info(green.wrap('  Raw screens captured under store_shots/raw/.')!)
        ..info('  ${styleDim.wrap('Now frame them: vgv screenshots <manifest>')}')
        ..info('');
    } else {
      _logger
        ..err('  Capture failed:')
        ..err(result.stdout.toString())
        ..err(result.stderr.toString());
    }
    return result.exitCode;
  }

  String _captureHarness() => r'''// Store screenshot capture harness (generated by `vgv screenshots capture`).
//
// Renders your screens at exact device sizes and writes raw PNGs that you then
// frame with:  vgv screenshots <manifest>
//
// HOW TO USE
//   1. Import your app's pages + DI setup below.
//   2. Replace each `Placeholder()` with the real screen (and pump any Bloc/
//      provider it needs).
//   3. Run:  vgv screenshots capture test/store_capture_test.dart
//      (which runs `flutter test --update-goldens`)
//   Raw PNGs are written to store_shots/raw/.

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

// import 'package:your_app/features/auth/presentation/pages/login_page.dart';

// Output size == logical size (devicePixelRatio pinned to 1).
const Size iphone = Size(1290, 2796);
const Size android = Size(1080, 1920);
const Size ipad = Size(2048, 2732);

Future<void> capture(
  WidgetTester tester,
  Size size,
  Widget screen,
  String out,
) async {
  tester.view.physicalSize = size;
  tester.view.devicePixelRatio = 1.0;
  addTearDown(tester.view.reset);
  await tester.pumpWidget(MaterialApp(home: screen));
  await tester.pumpAndSettle();
  await expectLater(find.byType(MaterialApp), matchesGoldenFile(out));
}

void main() {
  testWidgets('01 login (iphone)', (WidgetTester tester) async {
    // TODO: replace Placeholder() with your real screen, e.g. const LoginPage().
    await capture(tester, iphone, const Placeholder(), '../store_shots/raw/01.png');
  });

  testWidgets('02 login (android)', (WidgetTester tester) async {
    await capture(tester, android, const Placeholder(), '../store_shots/raw/02_android.png');
  });
}
''';

  Future<bool> _has(String cmd) async {
    try {
      final r = await Process.run('which', [cmd], runInShell: true);
      return r.exitCode == 0;
    } catch (_) {
      return false;
    }
  }

  void _init(String dir) {
    Directory(p.join(dir, 'raw')).createSync(recursive: true);
    Directory(p.join(dir, 'out')).createSync(recursive: true);
    final manifest = File(p.join(dir, 'manifest.json'));
    manifest.writeAsStringSync('''[
  {
    "device": "iphone",
    "type": "hero",
    "src": "raw/icon.png",
    "out": "out/00_hero.png",
    "headline": "Your app, **beautifully** framed",
    "subtitle": "Say what makes it great.",
    "accent": "#39D6E0"
  },
  {
    "device": "iphone",
    "type": "poster",
    "src": "raw/01.png",
    "out": "out/01.png",
    "headline": "A **clear** headline here",
    "subtitle": "One line of supporting copy.",
    "accent": "#39D6E0"
  },
  {
    "device": "android",
    "type": "poster",
    "src": "raw/01.png",
    "out": "out/01_android.png",
    "headline": "Also on **Android**",
    "subtitle": "Same engine, Android frame.",
    "accent": "#7C4DFF",
    "bg": "#141018"
  },
  {
    "type": "feature_graphic",
    "src": "raw/icon.png",
    "out": "out/feature_graphic.png",
    "headline": "Your app, in **one line**",
    "subtitle": "Play Store feature graphic (1024x500).",
    "accent": "#39D6E0"
  }
]
''');
    File(p.join(dir, 'README.md')).writeAsStringSync('''# Store screenshots

1. Drop your raw app screenshots in `raw/` (e.g. `raw/01.png`, `raw/icon.png`).
2. Edit `manifest.json`:
   - `device`: iphone | android | ipad | macbook | desktop
   - `type`: poster (frame + text) | hero (app icon + tagline) | frame (frame only)
     | duo (two frames side by side; needs `src2`)
     | feature_graphic (Play Store 1024x500 banner; `device` ignored)
   - `preset`: ocean | sunset | grape | forest | mono | gold (sets accent + bg)
   - `bg`: a hex color OR a path to an image (used as the background, with a scrim)
   - `locales`: `{ "en": {"headline":..,"subtitle":..}, "es": {...} }` renders one
     image per language (use `{locale}` in `out`, or it becomes a subfolder)
   - `headline`: wrap words in **double asterisks** to paint them with `accent`.
   - `accent` / `bg`: hex colors (bg optional; defaults to a tint of accent).
   - `width` + `height` (or `size: [w, h]`): optional — force an exact output
     size to match a store spec. Defaults are already store-accepted sizes.

## Store target sizes (portrait, no alpha — PNG/JPEG)

Defaults per device (override with width/height if your submission needs another):
- iPhone: 1290x2796 (App Store 6.7"/6.9" slot). Other accepted: 1260x2736, 1320x2868.
- iPad: 2048x2732 (12.9"); 13" is 2064x2752.
- Android phone: 1080x1920 (Play recommends 9:16; min 320, max 3840, max ≤ 2× min).
- Feature graphic (Google Play): 1024x500, fixed.

Outputs are written as RGB PNG (no alpha) as both stores require.

3. Render:
   ```bash
   vgv screenshots $dir/manifest.json
   ```
   Framed, store-ready PNGs land in `out/`.

Requires Python 3 + Pillow (`python3 -m pip install --user pillow`).
''');
    _logger
      ..info('')
      ..info(green.wrap('  Scaffolded $dir/'))
      ..info('    ${styleDim.wrap('raw/')}         drop your screenshots here')
      ..info('    ${styleDim.wrap('manifest.json')} edit headlines/devices/colors')
      ..info('    ${styleDim.wrap('out/')}         rendered posters')
      ..info('')
      ..info('  Then: ${lightCyan.wrap('vgv screenshots $dir/manifest.json')}')
      ..info('');
  }

  void _usage() {
    _logger
      ..info('')
      ..info(styleBold.wrap('  vgv screenshots — store marketing screenshots'))
      ..info('')
      ..info('  ${lightCyan.wrap('vgv screenshots web [--raw dir]')}     ${styleDim.wrap('open the visual editor (browser, no Python)')}')
      ..info('  ${lightCyan.wrap('vgv screenshots --init [dir]')}       ${styleDim.wrap('scaffold a manifest + folders')}')
      ..info('  ${lightCyan.wrap('vgv screenshots <manifest>')}         ${styleDim.wrap('render framed posters from a manifest')}')
      ..info('  ${lightCyan.wrap('vgv screenshots capture --init')}     ${styleDim.wrap('scaffold a golden harness to auto-capture raw screens')}')
      ..info('  ${lightCyan.wrap('vgv screenshots capture <test>')}     ${styleDim.wrap('run the harness (flutter test --update-goldens)')}')
      ..info('')
      ..info(styleDim.wrap('  Frames iPhone/Android/iPad/MacBook/desktop with backgrounds and'))
      ..info(styleDim.wrap('  headlines; also a Play Store feature graphic. Requires Python 3 + Pillow.'))
      ..info('');
  }
}
